###
GET http://localhost:3000/books HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3000/books/add HTTP/1.1
Content-Type: application/json

{
  "title": "title of the book",
  "author": "author of the book"
}

###
DELETE http://localhost:3000/books/delete/2 HTTP/1.1
Content-Type: application/json